#!/bin/bash

echo "🏛️  ACK Parish Web Application - Quick Start"
echo "============================================"
echo ""
echo "✅ Dependencies installed"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Get your Supabase anon key:"
echo "   Visit: https://supabase.com/dashboard/project/bcioubwyogptmotwdgty/settings/api"
echo "   Copy the 'anon public' key"
echo ""
echo "2. Update .env.local with your anon key"
echo ""
echo "3. Run database migrations:"
echo "   Visit: https://supabase.com/dashboard/project/bcioubwyogptmotwdgty/editor"
echo "   - Open SQL Editor"
echo "   - Run supabase/migrations/001_initial_schema.sql"
echo "   - Run supabase/migrations/002_rls_policies.sql"
echo ""
echo "4. Start the development server:"
echo "   npm run dev"
echo ""
echo "5. Open http://localhost:5173 in your browser"
echo ""
echo "📖 See SETUP.md for detailed instructions"
echo ""
